name: mate-deployment
run-name: ${{ github.actor }} - ${{ github.sha }}

on:
  push:
    branches:
     - main
     - develop
  pull_request:
    branches:
     - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.8

jobs:
  python-ci:
    runs-on: ubuntu-latest

    defaults:
     run:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setup Python ${{ env.PYTHON_VERSION }}
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install flake8 pytest pytest-cov
           pip install -r requirements.txt

      - name: Lint with flake8
        continue-on-error: true
        run: |
          cd ../
          flake8 . --show-source --statistics

      - name: Check Complexity
        continue-on-error: true
        run: |
          cd ../
          flake8 . --exit-zero --max-complexity=10 --statistics

      - name: Test with pytest
        run: |
          pytest -v --cov=. --cov-report=term-missing --cov-report=json

      - name: Upload code as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-source-code
          path: ./src

      - name: Output pipeline run link
        if: success()
        run: |
          echo "Pipeline run link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
